version: "3.7"
name: icedb-s3-proxy
volumes:
  minio_storage: null
  crdb_storage: null
services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
    command: server --console-address ":9001" /data
    container_name: minio
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 user password;
      /usr/bin/mc mb myminio/testbucket;
      exit 0;
      "
#  clickhouse:
#    image: clickhouse/clickhouse-server:latest
#    depends_on:
#      - minio
#      - crdb
#    container_name: ch
#    volumes:
#      - ./ch/user_scripts:/var/lib/clickhouse/user_scripts:0777
#      - /workspaces/icedb/ch/functions/get_files_function.xml:/etc/clickhouse-server/get_files_function.xml
